# Generated by Django 5.1 on 2024-09-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='school_id',
            new_name='school',
        ),
    ]
