# Generated by Django 5.1 on 2024-09-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_school_id_class_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='school',
            new_name='school_id',
        ),
    ]
