# Generated by Django 5.1 on 2024-09-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_school_class_school_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='school_id',
            new_name='school',
        ),
    ]
