# Generated by Django 5.1 on 2024-09-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_school_class_school_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='ClassBySchool',
        ),
    ]
