# Generated by Django 5.1 on 2024-09-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_student_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='avatar',
        ),
    ]
